Sushi\SushiBundle\Entity\DelZones:
    type: entity
    table: del_zones
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 15
            scale: 2
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        sortOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: sort_order
        css:
            type: string
            nullable: false
            length: 70
            options:
                fixed: false
    lifecycleCallbacks: {  }
