Sushi\SushiBundle\Entity\Groups:
    type: entity
    table: groups
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        orderGroup:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: order_group
    lifecycleCallbacks: {  }
